(define (problem nombre)
    (:domain desplazamientos-ext1)
    (:objects
   	  p0 p1 p2 p3 p4 p5 p6 p7 p8 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 - suministro
   	  a0 a1 a2 a3 a4 a5 a6 - asentamiento
   	  al0 al1 al2 al3 al4 - almacen
   	  r0 r1 r2 r3 r4 r5 r6 r7 - rover
    )
    (:init
   	 (basesAdyacentes a0 a2)
   	 (basesAdyacentes a0 al4)
   	 (basesAdyacentes a0 a5)
   	 (basesAdyacentes a0 al0)
   	 (basesAdyacentes a1 a2)
   	 (basesAdyacentes a1 a5)
   	 (basesAdyacentes a1 a6)
   	 (basesAdyacentes a1 al0)
   	 (basesAdyacentes a1 al1)
   	 (basesAdyacentes a1 al2)
   	 (basesAdyacentes a1 al3)
   	 (basesAdyacentes a1 al4)
   	 (basesAdyacentes a2 a0)
   	 (basesAdyacentes a2 a1)
   	 (basesAdyacentes a3 al4)
   	 (basesAdyacentes a4 al3)
   	 (basesAdyacentes a5 a0)
   	 (basesAdyacentes a5 a1)
   	 (basesAdyacentes a5 al1)
   	 (basesAdyacentes a6 a1)
   	 (basesAdyacentes a6 al3)
   	 (basesAdyacentes a6 al4)
   	 (basesAdyacentes a6 al0)
   	 (basesAdyacentes al0 al1)
   	 (basesAdyacentes al0 a1)
   	 (basesAdyacentes al0 a0)
   	 (basesAdyacentes al0 a6)
   	 (basesAdyacentes al1 a1)
   	 (basesAdyacentes al1 al3)
   	 (basesAdyacentes al1 a5)
   	 (basesAdyacentes al1 al0)
   	 (basesAdyacentes al2 a1)
   	 (basesAdyacentes al3 al1)
   	 (basesAdyacentes al3 a1)
   	 (basesAdyacentes al3 a4)
   	 (basesAdyacentes al3 a6)
   	 (basesAdyacentes al4 a0)
   	 (basesAdyacentes al4 a1)
   	 (basesAdyacentes al4 a3)
   	 (basesAdyacentes al4 a6)
   	 (posicionRecurso p0 a1)
   	 (posicionRecurso p1 a1)
   	 (posicionRecurso p2 a2)
   	 (posicionRecurso p3 a3)
   	 (posicionRecurso p4 a1)
   	 (posicionRecurso p5 a5)
   	 (posicionRecurso p6 a3)
   	 (posicionRecurso p7 a5)
   	 (posicionRecurso p8 a3)
   	 (posicionRecurso s0 al4)
   	 (posicionRecurso s1 al1)
   	 (posicionRecurso s2 al0)
   	 (posicionRecurso s3 al2)
   	 (posicionRecurso s4 al2)
   	 (posicionRecurso s5 al2)
   	 (posicionRecurso s6 al1)
   	 (posicionRecurso s7 al4)
   	 (posicionRecurso s8 al4)
   	 (posicionRecurso s9 al1)
   	 (peticion p0 a6)
   	 (peticion p1 a3)
   	 (peticion p2 a4)
   	 (peticion p3 a5)
   	 (peticion p4 a6)
   	 (peticion p5 a4)
   	 (peticion p6 a5)
   	 (peticion p7 a6)
   	 (peticion p8 a1)
   	 (peticion s0 al2)
   	 (peticion s1 al3)
   	 (peticion s2 al2)
   	 (peticion s3 al3)
   	 (peticion s4 al0)
   	 (peticion s5 al3)
   	 (peticion s6 al2)
   	 (peticion s7 al0)
   	 (peticion s8 al3)
   	 (peticion s9 al2)
   	 (peticion p6 a3)
   	 (peticion s9 al1)
   	 (peticion p1 a1)
   	 (peticion s5 al4)
   	 (peticion p1 a0)
   	 (peticion s0 al0)
   	 (peticion p1 a2)
   	 (peticion p4 a1)
   	 (peticion p1 a1)
   	 (peticion p6 a6)
   	 (posicionRover r0 a2) (= (numPersonas r0) 0)
   	 (posicionRover r1 al0) (= (numPersonas r1) 0)
   	 (posicionRover r2 a1) (= (numPersonas r2) 0)
   	 (posicionRover r3 a2) (= (numPersonas r3) 0)
   	 (posicionRover r4 a0) (= (numPersonas r4) 0)
   	 (posicionRover r5 al0) (= (numPersonas r5) 0)
   	 (posicionRover r6 a1) (= (numPersonas r6) 0)
   	 (posicionRover r7 al4) (= (numPersonas r7) 0)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
)