(define (problem nombre)
    (:domain desplazamientos-basico)
    (:objects
   	  p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 - suministro
   	  a0 a1 a2 a3 a4 a5 a6 - asentamiento
   	  al0 al1 al2 al3 al4 - almacen
   	  r0 r1 r2 r3 r4 r5 - rover
    )
    (:init
   	 (basesAdyacentes a0 a1)
   	 (basesAdyacentes a0 al4)
   	 (basesAdyacentes a1 a0)
   	 (basesAdyacentes a1 a4)
   	 (basesAdyacentes a2 a3)
   	 (basesAdyacentes a2 al4)
   	 (basesAdyacentes a3 al1)
   	 (basesAdyacentes a3 a2)
   	 (basesAdyacentes a3 a6)
   	 (basesAdyacentes a4 a1)
   	 (basesAdyacentes a4 al2)
   	 (basesAdyacentes a4 a6)
   	 (basesAdyacentes a5 a6)
   	 (basesAdyacentes a6 al3)
   	 (basesAdyacentes a6 a3)
   	 (basesAdyacentes a6 a4)
   	 (basesAdyacentes a6 a5)
   	 (basesAdyacentes al0 al1)
   	 (basesAdyacentes al1 a3)
   	 (basesAdyacentes al1 al0)
   	 (basesAdyacentes al2 al4)
   	 (basesAdyacentes al2 a4)
   	 (basesAdyacentes al3 a6)
   	 (basesAdyacentes al4 a0)
   	 (basesAdyacentes al4 al2)
   	 (basesAdyacentes al4 a2)
   	 (posicionRecurso p0 a3)
   	 (posicionRecurso p1 a6)
   	 (posicionRecurso p2 a2)
   	 (posicionRecurso p3 a1)
   	 (posicionRecurso p4 a5)
   	 (posicionRecurso p5 a2)
   	 (posicionRecurso p6 a5)
   	 (posicionRecurso p7 a4)
   	 (posicionRecurso p8 a0)
   	 (posicionRecurso p9 a0)
   	 (posicionRecurso s0 al2)
   	 (posicionRecurso s1 al0)
   	 (posicionRecurso s2 al3)
   	 (posicionRecurso s3 al4)
   	 (posicionRecurso s4 al1)
   	 (posicionRecurso s5 al1)
   	 (posicionRecurso s6 al0)
   	 (posicionRecurso s7 al4)
   	 (posicionRecurso s8 al1)
   	 (posicionRecurso s9 al1)
   	 (posicionRecurso s10 al2)
   	 (posicionRecurso s11 al3)
   	 (peticion p0 a5)
   	 (peticion p1 a3)
   	 (peticion p2 a4)
   	 (peticion p3 a4)
   	 (peticion p4 a5)
   	 (peticion p5 a6)
   	 (peticion p6 a3)
   	 (peticion p7 a4)
   	 (peticion p8 a0)
   	 (peticion p9 a3)
   	 (peticion s0 al3)
   	 (peticion s1 al0)
   	 (peticion s2 al1)
   	 (peticion s3 al3)
   	 (peticion s4 al4)
   	 (peticion s5 al0)
   	 (peticion s6 al1)
   	 (peticion s7 al2)
   	 (peticion s8 al1)
   	 (peticion s9 al2)
   	 (peticion s10 al2)
   	 (peticion s11 al0)
   	 (peticion p3 a0)
   	 (peticion s7 al0)
   	 (peticion s10 al2)
   	 (peticion s9 al4)
   	 (peticion p4 a6)
   	 (peticion s10 al1)
   	 (peticion s6 al2)
   	 (peticion p6 a5)
   	 (peticion s3 al1)
   	 (peticion s0 al0)
   	 (peticion p7 a0)
   	 (peticion s8 al0)
   	 (peticion s8 al3)
   	 (peticion p6 a3)
   	 (peticion p5 a1)
   	 (peticion s4 al0)
   	 (peticion s11 al1)
   	 (posicionRover r0 al0)
   	 (posicionRover r1 a6)
   	 (posicionRover r2 al0)
   	 (posicionRover r3 a1)
   	 (posicionRover r4 al0)
   	 (posicionRover r5 al1)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
)