(define (problem nombre)
    (:domain desplazamientos-ext3)
    (:objects
   	  p0 p1 p2 p3 p4 p5 p6 p7 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 - suministro
   	  a0 a1 a2 a3 a4 - asentamiento
   	  al0 al1 al2 al3 al4 al5 al6 al7 - almacen
   	  r0 r1 r2 r3 r4 - rover
    )
    (:init
   	 (basesAdyacentes a0 a2)
   	 (basesAdyacentes a0 a3)
   	 (basesAdyacentes a0 a4)
   	 (basesAdyacentes a0 al1)
   	 (basesAdyacentes a0 al3)
   	 (basesAdyacentes a1 a3)
   	 (basesAdyacentes a1 al0)
   	 (basesAdyacentes a1 al3)
   	 (basesAdyacentes a1 al5)
   	 (basesAdyacentes a1 al6)
   	 (basesAdyacentes a1 al7)
   	 (basesAdyacentes a2 a0)
   	 (basesAdyacentes a2 al0)
   	 (basesAdyacentes a2 al3)
   	 (basesAdyacentes a2 al4)
   	 (basesAdyacentes a2 al5)
   	 (basesAdyacentes a2 al6)
   	 (basesAdyacentes a3 a0)
   	 (basesAdyacentes a3 a1)
   	 (basesAdyacentes a3 a4)
   	 (basesAdyacentes a3 al1)
   	 (basesAdyacentes a3 al5)
   	 (basesAdyacentes a4 a0)
   	 (basesAdyacentes a4 a3)
   	 (basesAdyacentes a4 al0)
   	 (basesAdyacentes a4 al1)
   	 (basesAdyacentes a4 al4)
   	 (basesAdyacentes a4 al5)
   	 (basesAdyacentes a4 al6)
   	 (basesAdyacentes al0 a1)
   	 (basesAdyacentes al0 a2)
   	 (basesAdyacentes al0 a4)
   	 (basesAdyacentes al0 al3)
   	 (basesAdyacentes al0 al7)
   	 (basesAdyacentes al1 a0)
   	 (basesAdyacentes al1 a3)
   	 (basesAdyacentes al1 a4)
   	 (basesAdyacentes al1 al4)
   	 (basesAdyacentes al1 al5)
   	 (basesAdyacentes al1 al7)
   	 (basesAdyacentes al2 al4)
   	 (basesAdyacentes al3 a0)
   	 (basesAdyacentes al3 a1)
   	 (basesAdyacentes al3 a2)
   	 (basesAdyacentes al3 al0)
   	 (basesAdyacentes al3 al4)
   	 (basesAdyacentes al3 al7)
   	 (basesAdyacentes al4 a2)
   	 (basesAdyacentes al4 a4)
   	 (basesAdyacentes al4 al1)
   	 (basesAdyacentes al4 al2)
   	 (basesAdyacentes al4 al3)
   	 (basesAdyacentes al4 al5)
   	 (basesAdyacentes al4 al6)
   	 (basesAdyacentes al4 al7)
   	 (basesAdyacentes al5 a1)
   	 (basesAdyacentes al5 a2)
   	 (basesAdyacentes al5 a3)
   	 (basesAdyacentes al5 a4)
   	 (basesAdyacentes al5 al1)
   	 (basesAdyacentes al5 al4)
   	 (basesAdyacentes al5 al7)
   	 (basesAdyacentes al6 a1)
   	 (basesAdyacentes al6 a2)
   	 (basesAdyacentes al6 a4)
   	 (basesAdyacentes al6 al4)
   	 (basesAdyacentes al7 a1)
   	 (basesAdyacentes al7 al0)
   	 (basesAdyacentes al7 al1)
   	 (basesAdyacentes al7 al3)
   	 (basesAdyacentes al7 al4)
   	 (basesAdyacentes al7 al5)
   	 (posicionRecurso p0 a2)
   	 (posicionRecurso p1 a1)
   	 (posicionRecurso p2 a4)
   	 (posicionRecurso p3 a4)
   	 (posicionRecurso p4 a1)
   	 (posicionRecurso p5 a0)
   	 (posicionRecurso p6 a2)
   	 (posicionRecurso p7 a4)
   	 (posicionRecurso s0 al3)
   	 (posicionRecurso s1 al7)
   	 (posicionRecurso s2 al1)
   	 (posicionRecurso s3 al2)
   	 (posicionRecurso s4 al0)
   	 (posicionRecurso s5 al4)
   	 (posicionRecurso s6 al1)
   	 (posicionRecurso s7 al4)
   	 (posicionRecurso s8 al5)
   	 (posicionRecurso s9 al2)
   	 (posicionRecurso s10 al4)
   	 (posicionRecurso s11 al6)
   	 (posicionRecurso s12 al5)
   	 (posicionRecurso s13 al2)
   	 (peticion p0 a4) (= (prioridad p0 a4) 3)
   	 (peticion p1 a3) (= (prioridad p1 a3) 1)
   	 (peticion p2 a2) (= (prioridad p2 a2) 3)
   	 (peticion p3 a2) (= (prioridad p3 a2) 2)
   	 (peticion p4 a4) (= (prioridad p4 a4) 1)
   	 (peticion p5 a3) (= (prioridad p5 a3) 1)
   	 (peticion p6 a0) (= (prioridad p6 a0) 3)
   	 (peticion p7 a1) (= (prioridad p7 a1) 1)
   	 (peticion s0 al2) (= (prioridad s0 al2) 1)
   	 (peticion s1 al2) (= (prioridad s1 al2) 3)
   	 (peticion s2 al4) (= (prioridad s2 al4) 3)
   	 (peticion s3 al7) (= (prioridad s3 al7) 2)
   	 (peticion s4 al6) (= (prioridad s4 al6) 1)
   	 (peticion s5 al3) (= (prioridad s5 al3) 3)
   	 (peticion s6 al4) (= (prioridad s6 al4) 3)
   	 (peticion s7 al6) (= (prioridad s7 al6) 2)
   	 (peticion s8 al1) (= (prioridad s8 al1) 3)
   	 (peticion s9 al2) (= (prioridad s9 al2) 3)
   	 (peticion s10 al1) (= (prioridad s10 al1) 3)
   	 (peticion s11 al2) (= (prioridad s11 al2) 3)
   	 (peticion s12 al3) (= (prioridad s12 al3) 1)
   	 (peticion s13 al4) (= (prioridad s13 al4) 2)
   	 (peticion p3 a4) (= (prioridad p3 a4) 1)
   	 (peticion s13 al7) (= (prioridad s13 al7) 1)
   	 (peticion s13 al4) (= (prioridad s13 al4) 1)
   	 (peticion s13 al3) (= (prioridad s13 al3) 1)
   	 (peticion p7 a4) (= (prioridad p7 a4) 2)
   	 (peticion p2 a0) (= (prioridad p2 a0) 3)
   	 (peticion p2 a3) (= (prioridad p2 a3) 2)
   	 (peticion p2 a0) (= (prioridad p2 a0) 2)
   	 (posicionRover r0 al1) (= (numPersonas r0) 0) (= (combustible r0) 8)
   	 (posicionRover r1 al0) (= (numPersonas r1) 0) (= (combustible r1) 9)
   	 (posicionRover r2 a0) (= (numPersonas r2) 0) (= (combustible r2) 21)
   	 (posicionRover r3 al5) (= (numPersonas r3) 0) (= (combustible r3) 23)
   	 (posicionRover r4 al6) (= (numPersonas r4) 0) (= (combustible r4) 24)
 (= (sumaCombustible) 85)
 (= (sumaPrioridad) 0)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
    (:metric maximize  (sumaPrioridad))
)