(define (problem nombre)
    (:domain desplazamientos-ext2)
    (:objects
   	  p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 - suministro
   	  a0 a1 a2 a3 a4 a5 a6 a7 a8 - asentamiento
   	  al0 al1 al2 al3 al4 al5 - almacen
   	  r0 r1 r2 r3 - rover
    )
    (:init
   	 (basesAdyacentes a0 a1)
   	 (basesAdyacentes a0 a2)
   	 (basesAdyacentes a0 al5)
   	 (basesAdyacentes a1 a0)
   	 (basesAdyacentes a2 a0)
   	 (basesAdyacentes a3 a8)
   	 (basesAdyacentes a3 al0)
   	 (basesAdyacentes a3 a5)
   	 (basesAdyacentes a4 a5)
   	 (basesAdyacentes a4 a7)
   	 (basesAdyacentes a5 a3)
   	 (basesAdyacentes a5 a4)
   	 (basesAdyacentes a5 a6)
   	 (basesAdyacentes a5 al3)
   	 (basesAdyacentes a5 al4)
   	 (basesAdyacentes a6 al2)
   	 (basesAdyacentes a6 a5)
   	 (basesAdyacentes a6 a7)
   	 (basesAdyacentes a7 a8)
   	 (basesAdyacentes a7 a4)
   	 (basesAdyacentes a7 a6)
   	 (basesAdyacentes a7 al5)
   	 (basesAdyacentes a8 a3)
   	 (basesAdyacentes a8 a7)
   	 (basesAdyacentes al0 a3)
   	 (basesAdyacentes al0 al4)
   	 (basesAdyacentes al1 al3)
   	 (basesAdyacentes al2 a6)
   	 (basesAdyacentes al3 al1)
   	 (basesAdyacentes al3 al4)
   	 (basesAdyacentes al3 a5)
   	 (basesAdyacentes al4 al0)
   	 (basesAdyacentes al4 al3)
   	 (basesAdyacentes al4 a5)
   	 (basesAdyacentes al5 a0)
   	 (basesAdyacentes al5 a7)
   	 (posicionRecurso p0 a4)
   	 (posicionRecurso p1 a8)
   	 (posicionRecurso p2 a7)
   	 (posicionRecurso p3 a2)
   	 (posicionRecurso p4 a7)
   	 (posicionRecurso p5 a3)
   	 (posicionRecurso p6 a1)
   	 (posicionRecurso p7 a4)
   	 (posicionRecurso p8 a7)
   	 (posicionRecurso p9 a5)
   	 (posicionRecurso s0 al4)
   	 (posicionRecurso s1 al3)
   	 (posicionRecurso s2 al5)
   	 (posicionRecurso s3 al4)
   	 (posicionRecurso s4 al0)
   	 (posicionRecurso s5 al3)
   	 (posicionRecurso s6 al5)
   	 (posicionRecurso s7 al3)
   	 (posicionRecurso s8 al0)
   	 (posicionRecurso s9 al4)
   	 (peticion p0 a3)
   	 (peticion p1 a7)
   	 (peticion p2 a8)
   	 (peticion p3 a4)
   	 (peticion p4 a8)
   	 (peticion p5 a4)
   	 (peticion p6 a5)
   	 (peticion p7 a2)
   	 (peticion p8 a4)
   	 (peticion p9 a6)
   	 (peticion s0 al3)
   	 (peticion s1 al1)
   	 (peticion s2 al1)
   	 (peticion s3 al3)
   	 (peticion s4 al0)
   	 (peticion s5 al1)
   	 (peticion s6 al2)
   	 (peticion s7 al0)
   	 (peticion s8 al1)
   	 (peticion s9 al1)
   	 (peticion p0 a3)
   	 (peticion s2 al3)
   	 (peticion s0 al3)
   	 (peticion p0 a8)
   	 (peticion p6 a8)
   	 (peticion p2 a8)
   	 (peticion p8 a2)
   	 (peticion p9 a2)
   	 (peticion p9 a1)
   	 (peticion p4 a8)
   	 (peticion p0 a0)
   	 (peticion s2 al2)
   	 (peticion p9 a4)
   	 (peticion p5 a0)
   	 (peticion s0 al4)
   	 (peticion p1 a3)
   	 (peticion s2 al1)
   	 (posicionRover r0 a8) (= (numPersonas r0) 0) (= (combustible r0) 18)
   	 (posicionRover r1 al1) (= (numPersonas r1) 0) (= (combustible r1) 10)
   	 (posicionRover r2 a3) (= (numPersonas r2) 0) (= (combustible r2) 19)
   	 (posicionRover r3 al2) (= (numPersonas r3) 0) (= (combustible r3) 26)
 (= (sumaCombustible) 73)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
)