(define (problem nombre)
    (:domain desplazamientos-basico)
    (:objects
   	  p0 p1 p2 p3 p4 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 - suministro
   	  a0 a1 a2 a3 a4 a5 a6 - asentamiento
   	  al0 al1 al2 al3 al4 al5 al6 - almacen
   	  r0 r1 r2 r3 - rover
    )
    (:init
   	 (basesAdyacentes a0 al2)
   	 (basesAdyacentes a1 al1)
   	 (basesAdyacentes a1 al4)
   	 (basesAdyacentes a1 a5)
   	 (basesAdyacentes a2 al2)
   	 (basesAdyacentes a2 al3)
   	 (basesAdyacentes a2 al4)
   	 (basesAdyacentes a2 al5)
   	 (basesAdyacentes a3 al1)
   	 (basesAdyacentes a3 al0)
   	 (basesAdyacentes a4 al3)
   	 (basesAdyacentes a4 al6)
   	 (basesAdyacentes a4 al0)
   	 (basesAdyacentes a5 a1)
   	 (basesAdyacentes a5 a6)
   	 (basesAdyacentes a6 al6)
   	 (basesAdyacentes a6 a5)
   	 (basesAdyacentes al0 a3)
   	 (basesAdyacentes al0 a4)
   	 (basesAdyacentes al0 al5)
   	 (basesAdyacentes al1 a3)
   	 (basesAdyacentes al1 a1)
   	 (basesAdyacentes al1 al4)
   	 (basesAdyacentes al2 a0)
   	 (basesAdyacentes al2 a2)
   	 (basesAdyacentes al3 a2)
   	 (basesAdyacentes al3 a4)
   	 (basesAdyacentes al4 al1)
   	 (basesAdyacentes al4 a1)
   	 (basesAdyacentes al4 a2)
   	 (basesAdyacentes al5 a2)
   	 (basesAdyacentes al5 al0)
   	 (basesAdyacentes al6 a4)
   	 (basesAdyacentes al6 a6)
   	 (posicionRecurso p0 a0)
   	 (posicionRecurso p1 a6)
   	 (posicionRecurso p2 a3)
   	 (posicionRecurso p3 a4)
   	 (posicionRecurso p4 a5)
   	 (posicionRecurso s0 al3)
   	 (posicionRecurso s1 al0)
   	 (posicionRecurso s2 al1)
   	 (posicionRecurso s3 al2)
   	 (posicionRecurso s4 al6)
   	 (posicionRecurso s5 al0)
   	 (posicionRecurso s6 al5)
   	 (posicionRecurso s7 al0)
   	 (peticion p0 a1)
   	 (peticion p1 a4)
   	 (peticion p2 a2)
   	 (peticion p3 a4)
   	 (peticion p4 a6)
   	 (peticion s0 al6)
   	 (peticion s1 al2)
   	 (peticion s2 al5)
   	 (peticion s3 al4)
   	 (peticion s4 al5)
   	 (peticion s5 al4)
   	 (peticion s6 al2)
   	 (peticion s7 al1)
   	 (peticion p1 a6)
   	 (peticion p1 a4)
   	 (peticion s2 al6)
   	 (peticion s2 al1)
   	 (peticion p4 a3)
   	 (peticion s7 al0)
   	 (peticion p3 a2)
   	 (peticion p3 a1)
   	 (peticion p1 a3)
   	 (peticion p3 a1)
   	 (peticion p0 a6)
   	 (peticion p4 a2)
   	 (peticion s1 al6)
   	 (peticion s4 al5)
   	 (posicionRover r0 a2)
   	 (posicionRover r1 a4)
   	 (posicionRover r2 al6)
   	 (posicionRover r3 a1)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
)