(define (problem nombre)
    (:domain desplazamientos-ext1)
    (:objects
   	  p0 p1 p2 p3 p4 p5 p6 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 s8 - suministro
   	  a0 a1 a2 a3 a4 a5 - asentamiento
   	  al0 al1 al2 al3 al4 al5 - almacen
   	  r0 r1 r2 r3 r4 r5 - rover
    )
    (:init
   	 (basesAdyacentes a0 al5)
   	 (basesAdyacentes a0 al3)
   	 (basesAdyacentes a0 al4)
   	 (basesAdyacentes a0 a2)
   	 (basesAdyacentes a1 al2)
   	 (basesAdyacentes a1 a2)
   	 (basesAdyacentes a1 a4)
   	 (basesAdyacentes a2 a0)
   	 (basesAdyacentes a2 a1)
   	 (basesAdyacentes a2 al0)
   	 (basesAdyacentes a2 al1)
   	 (basesAdyacentes a2 al2)
   	 (basesAdyacentes a2 al5)
   	 (basesAdyacentes a3 al2)
   	 (basesAdyacentes a3 al4)
   	 (basesAdyacentes a3 a4)
   	 (basesAdyacentes a3 al1)
   	 (basesAdyacentes a4 a1)
   	 (basesAdyacentes a4 al4)
   	 (basesAdyacentes a4 a3)
   	 (basesAdyacentes a4 al1)
   	 (basesAdyacentes a5 al2)
   	 (basesAdyacentes al0 a2)
   	 (basesAdyacentes al0 al1)
   	 (basesAdyacentes al0 al2)
   	 (basesAdyacentes al0 al3)
   	 (basesAdyacentes al0 al4)
   	 (basesAdyacentes al1 a2)
   	 (basesAdyacentes al1 a3)
   	 (basesAdyacentes al1 a4)
   	 (basesAdyacentes al1 al0)
   	 (basesAdyacentes al1 al2)
   	 (basesAdyacentes al1 al3)
   	 (basesAdyacentes al1 al4)
   	 (basesAdyacentes al1 al5)
   	 (basesAdyacentes al2 a1)
   	 (basesAdyacentes al2 a2)
   	 (basesAdyacentes al2 a3)
   	 (basesAdyacentes al2 a5)
   	 (basesAdyacentes al2 al0)
   	 (basesAdyacentes al2 al1)
   	 (basesAdyacentes al2 al4)
   	 (basesAdyacentes al2 al5)
   	 (basesAdyacentes al3 a0)
   	 (basesAdyacentes al3 al5)
   	 (basesAdyacentes al3 al0)
   	 (basesAdyacentes al3 al1)
   	 (basesAdyacentes al4 a0)
   	 (basesAdyacentes al4 a3)
   	 (basesAdyacentes al4 a4)
   	 (basesAdyacentes al4 al0)
   	 (basesAdyacentes al4 al1)
   	 (basesAdyacentes al4 al2)
   	 (basesAdyacentes al4 al5)
   	 (basesAdyacentes al5 a0)
   	 (basesAdyacentes al5 a2)
   	 (basesAdyacentes al5 al1)
   	 (basesAdyacentes al5 al2)
   	 (basesAdyacentes al5 al3)
   	 (basesAdyacentes al5 al4)
   	 (posicionRecurso p0 a2)
   	 (posicionRecurso p1 a1)
   	 (posicionRecurso p2 a4)
   	 (posicionRecurso p3 a1)
   	 (posicionRecurso p4 a4)
   	 (posicionRecurso p5 a2)
   	 (posicionRecurso p6 a3)
   	 (posicionRecurso s0 al3)
   	 (posicionRecurso s1 al3)
   	 (posicionRecurso s2 al2)
   	 (posicionRecurso s3 al5)
   	 (posicionRecurso s4 al5)
   	 (posicionRecurso s5 al0)
   	 (posicionRecurso s6 al0)
   	 (posicionRecurso s7 al1)
   	 (posicionRecurso s8 al4)
   	 (peticion p0 a4)
   	 (peticion p1 a4)
   	 (peticion p2 a2)
   	 (peticion p3 a2)
   	 (peticion p4 a1)
   	 (peticion p5 a3)
   	 (peticion p6 a4)
   	 (peticion s0 al1)
   	 (peticion s1 al1)
   	 (peticion s2 al5)
   	 (peticion s3 al0)
   	 (peticion s4 al3)
   	 (peticion s5 al2)
   	 (peticion s6 al4)
   	 (peticion s7 al2)
   	 (peticion s8 al2)
   	 (peticion s1 al0)
   	 (peticion s3 al4)
   	 (peticion p4 a5)
   	 (peticion p2 a4)
   	 (peticion s7 al1)
   	 (peticion p5 a3)
   	 (peticion s0 al3)
   	 (peticion s4 al3)
   	 (peticion s3 al2)
   	 (peticion p4 a0)
   	 (posicionRover r0 a1) (= (numPersonas r0) 0)
   	 (posicionRover r1 al2) (= (numPersonas r1) 0)
   	 (posicionRover r2 a5) (= (numPersonas r2) 0)
   	 (posicionRover r3 al0) (= (numPersonas r3) 0)
   	 (posicionRover r4 al4) (= (numPersonas r4) 0)
   	 (posicionRover r5 al4) (= (numPersonas r5) 0)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
)