(define (problem nombre)
    (:domain desplazamientos-ext3)
    (:objects
   	  p0 p1 p2 p3 p4 - persona
   	  s0 s1 s2 s3 s4 - suministro
   	  a0 a1 a2 a3 a4 a5 a6 a7 a8 - asentamiento
   	  al0 al1 al2 al3 al4 - almacen
   	  r0 r1 r2 r3 r4 r5 - rover
    )
    (:init
   	 (basesAdyacentes a0 al0)
   	 (basesAdyacentes a1 al4)
   	 (basesAdyacentes a2 a8)
   	 (basesAdyacentes a2 a6)
   	 (basesAdyacentes a3 a8)
   	 (basesAdyacentes a3 al1)
   	 (basesAdyacentes a3 al3)
   	 (basesAdyacentes a3 a6)
   	 (basesAdyacentes a4 a8)
   	 (basesAdyacentes a4 al0)
   	 (basesAdyacentes a5 a8)
   	 (basesAdyacentes a6 a8)
   	 (basesAdyacentes a6 a2)
   	 (basesAdyacentes a6 a3)
   	 (basesAdyacentes a7 al1)
   	 (basesAdyacentes a7 al4)
   	 (basesAdyacentes a8 a2)
   	 (basesAdyacentes a8 a3)
   	 (basesAdyacentes a8 a4)
   	 (basesAdyacentes a8 a5)
   	 (basesAdyacentes a8 a6)
   	 (basesAdyacentes al0 a0)
   	 (basesAdyacentes al0 a4)
   	 (basesAdyacentes al1 a3)
   	 (basesAdyacentes al1 al3)
   	 (basesAdyacentes al1 a7)
   	 (basesAdyacentes al2 al4)
   	 (basesAdyacentes al3 al1)
   	 (basesAdyacentes al3 a3)
   	 (basesAdyacentes al4 a1)
   	 (basesAdyacentes al4 al2)
   	 (basesAdyacentes al4 a7)
   	 (posicionRecurso p0 a1)
   	 (posicionRecurso p1 a5)
   	 (posicionRecurso p2 a1)
   	 (posicionRecurso p3 a3)
   	 (posicionRecurso p4 a1)
   	 (posicionRecurso s0 al1)
   	 (posicionRecurso s1 al0)
   	 (posicionRecurso s2 al3)
   	 (posicionRecurso s3 al2)
   	 (posicionRecurso s4 al0)
   	 (peticion p0 a6) (= (prioridad p0 a6) 1)
   	 (peticion p1 a4) (= (prioridad p1 a4) 1)
   	 (peticion p2 a8) (= (prioridad p2 a8) 1)
   	 (peticion p3 a8) (= (prioridad p3 a8) 1)
   	 (peticion p4 a5) (= (prioridad p4 a5) 1)
   	 (peticion s0 al1) (= (prioridad s0 al1) 3)
   	 (peticion s1 al4) (= (prioridad s1 al4) 3)
   	 (peticion s2 al4) (= (prioridad s2 al4) 1)
   	 (peticion s3 al4) (= (prioridad s3 al4) 1)
   	 (peticion s4 al3) (= (prioridad s4 al3) 3)
   	 (peticion s1 al1) (= (prioridad s1 al1) 1)
   	 (peticion p4 a6) (= (prioridad p4 a6) 3)
   	 (peticion s2 al3) (= (prioridad s2 al3) 3)
   	 (peticion p3 a1) (= (prioridad p3 a1) 2)
   	 (peticion s3 al2) (= (prioridad s3 al2) 1)
   	 (peticion p1 a1) (= (prioridad p1 a1) 2)
   	 (peticion s4 al4) (= (prioridad s4 al4) 3)
   	 (peticion p0 a3) (= (prioridad p0 a3) 1)
   	 (peticion s3 al3) (= (prioridad s3 al3) 1)
   	 (peticion s0 al0) (= (prioridad s0 al0) 2)
   	 (peticion p1 a8) (= (prioridad p1 a8) 2)
   	 (peticion s1 al3) (= (prioridad s1 al3) 1)
   	 (peticion s2 al3) (= (prioridad s2 al3) 2)
   	 (peticion p0 a2) (= (prioridad p0 a2) 1)
   	 (peticion s0 al1) (= (prioridad s0 al1) 3)
   	 (peticion s2 al0) (= (prioridad s2 al0) 1)
   	 (peticion p3 a7) (= (prioridad p3 a7) 2)
   	 (posicionRover r0 a4) (= (numPersonas r0) 0) (= (combustible r0) 28)
   	 (posicionRover r1 a2) (= (numPersonas r1) 0) (= (combustible r1) 24)
   	 (posicionRover r2 a2) (= (numPersonas r2) 0) (= (combustible r2) 5)
   	 (posicionRover r3 al1) (= (numPersonas r3) 0) (= (combustible r3) 18)
   	 (posicionRover r4 a7) (= (numPersonas r4) 0) (= (combustible r4) 20)
   	 (posicionRover r5 a0) (= (numPersonas r5) 0) (= (combustible r5) 6)
 (= (sumaCombustible) 101)
 (= (sumaPrioridad) 0)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
    (:metric maximize (+ (* 10 (sumaPrioridad)) (* 8 (sumaCombustible))))
)