(define (problem nombre)
    (:domain desplazamientos-ext2)
    (:objects
   	  p0 p1 p2 p3 p4 p5 - persona
   	  s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 - suministro
   	  a0 a1 a2 a3 a4 a5 - asentamiento
   	  al0 al1 al2 al3 al4 al5 al6 al7 al8 - almacen
   	  r0 r1 r2 r3 r4 r5 - rover
    )
    (:init
   	 (basesAdyacentes a0 a2)
   	 (basesAdyacentes a0 a5)
   	 (basesAdyacentes a0 al7)
   	 (basesAdyacentes a0 al8)
   	 (basesAdyacentes a1 al6)
   	 (basesAdyacentes a2 a0)
   	 (basesAdyacentes a2 a3)
   	 (basesAdyacentes a2 a4)
   	 (basesAdyacentes a3 a2)
   	 (basesAdyacentes a3 al4)
   	 (basesAdyacentes a3 a4)
   	 (basesAdyacentes a3 a5)
   	 (basesAdyacentes a4 a2)
   	 (basesAdyacentes a4 a3)
   	 (basesAdyacentes a4 al5)
   	 (basesAdyacentes a4 al6)
   	 (basesAdyacentes a4 al8)
   	 (basesAdyacentes a5 a0)
   	 (basesAdyacentes a5 al3)
   	 (basesAdyacentes a5 a3)
   	 (basesAdyacentes al0 al3)
   	 (basesAdyacentes al0 al1)
   	 (basesAdyacentes al1 al5)
   	 (basesAdyacentes al1 al6)
   	 (basesAdyacentes al1 al7)
   	 (basesAdyacentes al1 al0)
   	 (basesAdyacentes al2 al3)
   	 (basesAdyacentes al2 al6)
   	 (basesAdyacentes al3 al2)
   	 (basesAdyacentes al3 al7)
   	 (basesAdyacentes al3 a5)
   	 (basesAdyacentes al3 al0)
   	 (basesAdyacentes al4 a3)
   	 (basesAdyacentes al4 al8)
   	 (basesAdyacentes al5 a4)
   	 (basesAdyacentes al5 al7)
   	 (basesAdyacentes al5 al1)
   	 (basesAdyacentes al6 al2)
   	 (basesAdyacentes al6 a1)
   	 (basesAdyacentes al6 a4)
   	 (basesAdyacentes al6 al1)
   	 (basesAdyacentes al7 a0)
   	 (basesAdyacentes al7 al1)
   	 (basesAdyacentes al7 al3)
   	 (basesAdyacentes al7 al5)
   	 (basesAdyacentes al7 al8)
   	 (basesAdyacentes al8 a0)
   	 (basesAdyacentes al8 al4)
   	 (basesAdyacentes al8 a4)
   	 (basesAdyacentes al8 al7)
   	 (posicionRecurso p0 a4)
   	 (posicionRecurso p1 a4)
   	 (posicionRecurso p2 a2)
   	 (posicionRecurso p3 a0)
   	 (posicionRecurso p4 a3)
   	 (posicionRecurso p5 a0)
   	 (posicionRecurso s0 al7)
   	 (posicionRecurso s1 al8)
   	 (posicionRecurso s2 al4)
   	 (posicionRecurso s3 al6)
   	 (posicionRecurso s4 al2)
   	 (posicionRecurso s5 al7)
   	 (posicionRecurso s6 al3)
   	 (posicionRecurso s7 al5)
   	 (posicionRecurso s8 al2)
   	 (posicionRecurso s9 al4)
   	 (posicionRecurso s10 al4)
   	 (posicionRecurso s11 al0)
   	 (posicionRecurso s12 al3)
   	 (posicionRecurso s13 al6)
   	 (peticion p0 a3)
   	 (peticion p1 a3)
   	 (peticion p2 a2)
   	 (peticion p3 a2)
   	 (peticion p4 a2)
   	 (peticion p5 a2)
   	 (peticion s0 al6)
   	 (peticion s1 al4)
   	 (peticion s2 al4)
   	 (peticion s3 al5)
   	 (peticion s4 al2)
   	 (peticion s5 al3)
   	 (peticion s6 al4)
   	 (peticion s7 al4)
   	 (peticion s8 al4)
   	 (peticion s9 al4)
   	 (peticion s10 al2)
   	 (peticion s11 al7)
   	 (peticion s12 al0)
   	 (peticion s13 al6)
   	 (peticion s8 al6)
   	 (peticion p4 a3)
   	 (peticion p2 a5)
   	 (peticion p3 a2)
   	 (peticion p3 a1)
   	 (peticion s11 al2)
   	 (peticion s13 al4)
   	 (peticion p3 a4)
   	 (peticion s2 al4)
   	 (posicionRover r0 al8) (= (numPersonas r0) 0) (= (combustible r0) 2)
   	 (posicionRover r1 al8) (= (numPersonas r1) 0) (= (combustible r1) 14)
   	 (posicionRover r2 al5) (= (numPersonas r2) 0) (= (combustible r2) 25)
   	 (posicionRover r3 al7) (= (numPersonas r3) 0) (= (combustible r3) 15)
   	 (posicionRover r4 al3) (= (numPersonas r4) 0) (= (combustible r4) 6)
   	 (posicionRover r5 al1) (= (numPersonas r5) 0) (= (combustible r5) 7)
 (= (sumaCombustible) 69)
    )
    (:goal (forall (?r - recurso) (entregado ?r)))
    (:metric maximize  (sumaCombustible))
)